language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run generate
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x deploy.sh && ./deploy.sh
  on:
    branch: develop
branches:
  only:
  - develop
env:
  global:
  - COMMIT_AUTHOR_EMAIL: pc.poisoning@gmail.com
  - GH_ACOUNT: histudy
  - GH_REPO: histudy.github.io
  - GH_BRANCH: master
  - secure: mP6Jdpc8yfsDO5tZh39ZpU9uxWHJkmLOpNQEr4etPG1s/9tAzE1WXZJQyldlbzTucDgEsIj+8Rhxt4742dgVDKF3Yx/D2GTpEDIOnj40gz552jc0xyqPm/LaCKFV9jnCQHlhE4ie0+b4wtPz1hRqjHd+XLztRlVfdZotU/JxV3fyVWHF+iXbGZUfjGyTBFv4sTgE1KCyMP9nQ+nGFz0I18EOKjmFTiAPd4EECv7PsPg7PhCzl9DrV+hOK7bW1FrJzZgMMx1f2NKuXADIXx/fvgATGMTJL/RAVUK+7hscT5FB81b7IkszNNJKWSihJ1UX/srhJ1uSdo6V5ll14zkclSNn4qYxl98AcJeGWqEQjQ6pMVgwXPs7YHJSg90eBAwBdJ8wo4MNy3f5n9CK3bD9K04lz2LM9iZ43QQOfd/nXqmwBrn8s3cqEtwhur7hejF7ddxcbfEbx4S1errfMEYo2uRGvTxviptQ38FmMX151VGiDBZd6g4xbnN7M2r4PXMfvR0BBS5kcf0U6fKPciEIuuxrSSLwCGK8swt2ps6kCmXQFQn89tT3svdwSrkmLMViMNOd8BrsM+xxZB++TBQ1D5xKHi8ajuywLLq9nHw6boKFLJbmGddd+KAj5a+RIpKH1S8+0gQ88svaPMXq7i5qTfXk2dDEPjgYfu338vUGhbc=
