baseURL: 'https://histudy.jp/'
title: '姫路IT系勉強会'

defaultContentLanguage: 'ja'
languageCode: 'ja'
hasCJKLanguage: true

theme: binario

archetypeDir: scaffolds

menu:
  main:
  - identifier: logs
    name: 開催履歴
    url: /categories/開催履歴/
    weight: -40

  - identifier: topic
    name: Topics
    url: /topic/
    weight: -20

  - identifier: about
    name: About
    url: /about/
    weight: 0

Params:
  mainSections:
    - meeting-logs
  colorTheme: dark-green
  Social:
    github: "histudy"

