baseURL: 'https://histudy.jp/'
title: '姫路IT系勉強会'

defaultContentLanguage: 'ja'
languageCode: 'ja'
hasCJKLanguage: true

theme: binario

archetypeDir: scaffolds

menu:
  main:
  - identifier: about
    name: About
    url: /about/

  - identifier: topic
    name: Topics
    url: /topic/
