# CircleCI 2.0 configuration file
#
# Environment Variables
#
#  HOST_NAME
#  USER_NAME
#  HOST_DEPLOY_PATH
#  SSH_PORT (Optional)
#
version: 2
general:
  branches:
    ignore:
      - master

## ------------------
## ビルド環境
## ------------------
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.12.0-stretch

## ------------------
## デプロイ用SSH鍵の設定
## ------------------
deploy_ssh_keys: &deploy_ssh_keys
  - "66:12:d3:6b:b1:87:5e:84:32:22:14:f6:ad:36:b4:ed"

jobs:
  deploy:
    <<: *defaults
    steps:
      - run:
          name: install rsync
          command: sudo apt-get update && sudo apt-get install -y rsync
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: make public directory
          command: mkdir -p ~/repo/public && mkdir -p ~/repo/node_modules
      - run:
          name: install hexo-cli
          command: sudo npm install -g hexo-cli
      - run:
          name: install npm
          command: cd ~/repo && npm install
      - run:
          name: generate npm
          command: cd ~/repo && hexo generate --force
      - add_ssh_keys:
          fingerprints: *deploy_ssh_keys
      - run:
          name: check .ssh
          command: cat ~/.ssh/config
      - run:
          name: ssh-keyscan
          command: ssh-keyscan ${HOST_NAME} -p ${SSH_PORT:-22}  >> ~/.ssh/known_hosts && cat ~/.ssh/known_hosts
      - run:
          name: run deploy batch
          command: rsync -rlOtcv --delete -e "ssh -p ${SSH_PORT:-22}" ~/repo/public/ ${USER_NAME}@${HOST_NAME}:${HOST_DEPLOY_PATH}
workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: master
