version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
# -------------
# ジョブの設定
# -------------
jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run generate
      - persist_to_workspace:
          root: ~/repo
          paths:
            - public
  deploy:
    executor: default
    steps:
      - attach_workspace:
          at: ./
      - run: ls -la
      # - add_ssh_keys:
      #     fingerprints:
      #       - "xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx"
      # - run:
      #     name: Start ssh-keyscan
      #     command: |
      #       ssh-keyscan -p ${SSH_PORT:-22} ${HOST_NAME} >> ~/.ssh/known_hosts
      # - deploy:
      #     name: Start deploy
      #     command: |
      #       rsync -av --delete --rsh="ssh -p ${SSH_PORT:-22}" ./public/ ${USER_NAME}@${HOST_NAME}:${HOST_PATH:-/var/www/html/}

# -------------
# ワークフローの設定
# -------------
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
