version: 2.1
# -------------
# 実行環境
# -------------
executors:
  default:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    # environment:
    #   # 以下の環境変数を管理画面から設定すること
    #   # ※デプロイ先の接続情報は適時読み替えてください
    #   USER_NAME: circleci
    #   HOST_NAME: histudy.jp
    #   HOST_PATH: /var/www/html/
    #   SSH_PORT: 22
# -------------
# デプロイ用SSH鍵の設定
# -------------
deploy_ssh_keys: &deploy_ssh_keys
  # 以下のCirleCIに登録したSSH鍵ののフィンガープリントを記載する
  - "xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx"
# -------------
# ジョブの設定
# -------------
jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run generate
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./
  deploy:
    executor: default
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install rsync
          command: sudo apt-get install -y rsync
      - add_ssh_keys:
          fingerprints: *deploy_ssh_keys
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan -p ${SSH_PORT:-22} ${HOST_NAME} >> ~/.ssh/known_hosts
      - deploy:
          name: Start deploy
          command: |
            rsync -av --delete --rsh="ssh -p ${SSH_PORT:-22}" ./public/ ${USER_NAME}@${HOST_NAME}:${HOST_PATH:-/var/www/html/}

# -------------
# ワークフローの設定
# -------------
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
