# CircleCI 2.0 configuration file
#
# Environment Variables
#
#  HOST_NAME
#  USER_NAME
#  HOST_DEPLOY_PATH
#  SSH_PORT (Optional)
#
version: 2.1
general:
  branches:
    only:
      - master

jobs:
  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - attach_workspace:
            at: .
      - add_ssh_keys:
          fingerprints: 
            - "3a:66:3f:f0:d9:6b:82:77:70:ad:e2:6d:88:88:61:44"
      - run:
          name: Add known host
          command: ssh-keyscan $HOST_NAME >> ~/.ssh/known_hosts
      - run:
          name: install rsync
          command: sudo apt update && sudo apt install -y rsync
      - run:
          name: deploy by rsync
          command: rsync -rlOtcv --delete --checksum -e ssh ./public/ $USER_NAME@$HOST_NAME:$HOST_DEPLOY_PATH
orbs:
  hugo: circleci/hugo@1.2.2
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: false
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build
