# CircleCI 2.0 configuration file
version: 2
general:
  branches:
    ignore:
      - master
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1
jobs:
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: run deploy batch
          command: deploy.sh
workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy:

