# CircleCI 2.0 configuration file
version: 2
general:
  branches:
    ignore:
      - master
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.12.0-stretch
jobs:
  deploy:
    <<: *defaults
    steps:
      - run:
          name: install rsync
          command: sudo apt-get update && sudo apt-get install -y rsync
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: make public directory
          command: mkdir -p ~/repo/public && mkdir -p ~/repo/node_modules
      - run:
          name: install hexo-cli
          command: sudo npm install -g hexo-cli
      - run:
          name: install npm
          command: cd ~/repo && npm install
      - run:
          name: generate npm
          command: cd ~/repo && hexo generate --force
      - add_ssh_keys:
          fingerprints:
            - "66:12:d3:6b:b1:87:5e:84:32:22:14:f6:ad:36:b4:ed"
      - run:
          name: check .ssh
          command: cat ~/.ssh/config
      - run:
          name: ssh-keyscan
          command: ssh-keyscan -p 22 histudy.jp >> ~/.ssh/known_hosts && cat ~/.ssh/known_hosts
      - run:
          name: run deploy batch
          command: rsync -auz --delete -e ssh ~/repo/public/ 223n@histudy.jp:/tmp/www/html/
workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: master
