# CircleCI 2.0 configuration file
version: 2
general:
  branches:
    ignore:
      - master
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1
jobs:
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: echo git version
          command: git --version
      - run:
          name: run deploy batch
          command: ~/repo/deploy.sh
workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: master
